#! /bin/bash

action=$1
shift

case "$action" in
	# "Standard" action commands, used regularly
	search | -s)
		eix "$@"
		;;
	install | -i)
		emerge -av "$@"
		;;
	remove | uninstall | -r)
		emerge --depclean -av "$@"
		;;
	update)
		eix-sync "$@"
		;;
	upgrade | dist-upgrade)
		# Make it portage 2.1-safe and make sure it catches EVERYTHING.
		emerge -uDvaN --with-bdeps=y @system world "$@"
		;;
	autoremove)
		emerge --depclean -a "$@"
		;;
	autoclean)
		# Keep fetch-restricted distfiles, because refetching is painful
		eclean-dist -df "$@"
		;;
	clean)
		DISTDIR=$(portageq distdir)
		read -n 1 -p "Are you sure you'd like to remove ALL files and folders within ${DISTDIR}? [yN] "
		echo;
		if [ "$REPLY" = 'y' -o "$REPLY" = 'Y' ]; then
			rm -rf $DISTDIR/* "$@"
		fi
		;;
	forceremove)
		emerge --unmerge -av "$@"
		;;
	# info commands
	listfiles)
		equery files "$@"
		;;
	listinstalled)
		equery list "$@"
		;;
	provides)
		equery belongs "$@"
		;;
	verify)
		equery check -o "$@"
		;;
	verifyall)
		equery check -o '*' "$@"
		;;
	# random commands
	moo)
		emerge --moo
		;;
	machinegod)
		echo "Only the zmedico can fix your machine god."
		;;
	sysinfo)
		emerge --info "$@"
		;;
	# fallthrough
	*)
		echo "Usage: epkg install|remove|uninstall|update|upgrade|dist-upgrade|search|listfiles|listinstalled|provides|verify|verifyall|sysinfo|forceremove|autoclean|clean [package(s)]"
		;;
esac
